apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: nginx
  labels: 
    app: simple-pod
    color: blue
spec: 
  containers:
  - name: my-app-container
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: nginx
  labels:
    color: blue
spec:
  selector:
    app: simple-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
